import httpService from '@/lib/http-service';
import { API_CONFIG } from '@/constants/constants';

export type DowntimeClassification = 'OUTAGE' | 'EXCLUDED';

export type DowntimeReasonCode =
  | 'COMMUNICATION_LOSS'
  | 'UTILITY_OUTAGE'
  | 'ISP_OUTAGE'
  | 'VANDALISM'
  | 'FORCE_MAJEURE'
  | 'SCHEDULED_MAINTENANCE'
  | 'VEHICLE_ERROR'
  | 'UNKNOWN';

export interface ConnectorDowntimeInterval {
  id: string;
  connectorId: string;
  stationId: string;
  startTime: string;
  endTime: string | null;
  durationSeconds: number | null;
  classification: DowntimeClassification;
  reasonCode: DowntimeReasonCode;
  autoGenerated: boolean;
  overriddenBy: string | null;
  overrideNotes: string | null;
  evidence: string | null;
  ticketNumber: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface OverrideDowntimeDto {
  classification: DowntimeClassification;
  reason: DowntimeReasonCode;
  notes: string;
  evidence?: string;
  ticketNumber?: string;
}

export interface UptimeCalculationResponse {
  connectorId: string;
  totalTimeSeconds: number;
  excludedTimeSeconds: number;
  outageTimeSeconds: number;
  uptimePercentage: number;
}

export interface ComplianceReportItem {
  connectorId: string;
  evseId: string;
  connectorPortId: number;
  date?: string;
  month?: string;
  quarter?: string;
  totalTimeSeconds: number;
  excludedTimeSeconds: number;
  outageTimeSeconds: number;
  uptimePercentage: number;
}

class ComplianceService {
  /** GET /compliance/uptime */
  async calculateUptime(
    connectorId: string,
    startDate: string,
    endDate: string,
  ): Promise<UptimeCalculationResponse> {
    return httpService.get<UptimeCalculationResponse>(API_CONFIG.endpoints.compliance.uptime, {
      params: {
        connectorId,
        startDate,
        endDate,
      },
    });
  }

  /** GET /compliance/downtime/intervals */
  async getDowntimeIntervals(
    connectorId?: string,
    limit?: number,
    offset?: number,
  ): Promise<ConnectorDowntimeInterval[]> {
    return httpService.get<ConnectorDowntimeInterval[]>(
      API_CONFIG.endpoints.compliance.downtimeIntervals,
      {
        params: {
          connectorId,
          limit,
          offset,
        },
      },
    );
  }

  /** POST /compliance/downtime/:id/override */
  async overrideDowntime(
    intervalId: string,
    data: OverrideDowntimeDto,
  ): Promise<ConnectorDowntimeInterval> {
    return httpService.post<ConnectorDowntimeInterval>(
      API_CONFIG.endpoints.compliance.override(intervalId),
      data,
    );
  }

  /** GET /reports/daily */
  async getDailyReport(
    startDate: string,
    endDate: string,
    params?: { connectorId?: string; stationId?: string },
  ): Promise<ComplianceReportItem[]> {
    return httpService.get<ComplianceReportItem[]>(API_CONFIG.endpoints.compliance.dailyReport, {
      params: {
        startDate,
        endDate,
        ...params,
      },
    });
  }

  /** GET /reports/monthly */
  async getMonthlyReport(
    startDate: string,
    endDate: string,
    params?: { connectorId?: string; stationId?: string },
  ): Promise<ComplianceReportItem[]> {
    return httpService.get<ComplianceReportItem[]>(API_CONFIG.endpoints.compliance.monthlyReport, {
      params: {
        startDate,
        endDate,
        ...params,
      },
    });
  }

  /** GET /reports/quarterly */
  async getQuarterlyReport(
    startDate: string,
    endDate: string,
    params?: { connectorId?: string; stationId?: string },
  ): Promise<ComplianceReportItem[]> {
    return httpService.get<ComplianceReportItem[]>(
      API_CONFIG.endpoints.compliance.quarterlyReport,
      {
        params: {
          startDate,
          endDate,
          ...params,
        },
      },
    );
  }
}

export const complianceService = new ComplianceService();
